#!/usr/bin/env bun
/**
 * tokens: turn design/tokens.json into the CSS custom properties the site draws with.
 *
 * `design/tokens.json` is the only place a colour, a size or a spacing value is defined, and that
 * has to stay true for the website too — otherwise the site is a fifteenth hand-maintained copy of
 * the palette and drifts the first time a token moves. So nothing here invents a value: it flattens
 * the three layers into `--palette-*`, `--color-*` and `--purpose-*`, resolving `{a.b.c}` aliases to
 * a `var()` reference rather than to a hex, so the layering survives into the stylesheet and the
 * browser inspector shows the same chain the canvas describes.
 *
 * Only colour, space and radius cross over. The type ramp does not: the dash's sizes are pixels on
 * a 480 px screen and mean nothing in a browser, and the ui ramp is the plugin's, at 96 dpi.
 * The site's own ramp lives in app/globals.css, built on the same two families.
 *
 * Written to app/tokens.css, which is generated and gitignored; `bun run build` runs this first.
 */
import { mkdirSync, writeFileSync } from 'node:fs';
import path from 'node:path';

const repoRoot = path.resolve(import.meta.dir, '..', '..');
const tokensPath = path.join(repoRoot, 'design', 'tokens.json');
const outPath = path.resolve(import.meta.dir, '..', 'app', 'tokens.css');

type Node = { value?: unknown; [key: string]: unknown };

/** `palette.grey.600` -> `--palette-grey-600`. */
const varName = (dotted: string): string => `--${dotted.replace(/\./g, '-')}`;

/** A token value is either a literal or `{a.b.c}`, an alias into another token. */
const cssValue = (value: string): string => {
  const alias = value.match(/^\{([^}]+)\}$/);
  return alias ? `var(${varName(alias[1]!)})` : value;
};

/** Every leaf under a subtree, in declaration order, as `[dotted, value]`. */
export function flatten(node: unknown, prefix: string[] = []): [string, string][] {
  if (node === null || typeof node !== 'object' || Array.isArray(node)) return [];
  const record = node as Node;
  // A token is an object carrying a scalar `value`; everything else is a group to descend into.
  if ('value' in record && typeof record.value !== 'object') {
    return [[prefix.join('.'), String(record.value)]];
  }
  return Object.entries(record)
    .filter(([key]) => !key.startsWith('$'))
    .flatMap(([key, child]) => flatten(child, [...prefix, key]));
}

/** One `--name: value;` block, with the layer named above it. */
function block(title: string, note: string, entries: [string, string][]): string {
  const body = entries.map(([dotted, value]) => `  ${varName(dotted)}: ${cssValue(value)};`).join('\n');
  return `  /* ${title}\n   * ${note} */\n${body}\n`;
}

export function stylesheet(tokens: Record<string, unknown>): string {
  const scale = (group: Record<string, unknown>, prefix: string, unit: string): [string, string][] =>
    Object.entries(group).map(([key, value]) => [`${prefix}.${key}`, `${value}${value === 0 ? '' : unit}`]);

  return `/*
 * Generated by site/scripts/tokens.ts from design/tokens.json ${(tokens.$meta as Node)?.version ?? ''}.
 * Do not edit: change the token and run \`bun run tokens\` in site/.
 *
 * The aliases are kept as aliases. --purpose-delta-slower resolves to --color-danger-primary, which
 * resolves to --palette-red-200, exactly as the design canvas describes the three layers, so a
 * colour changed at the palette moves everything named after it.
 */
:root {
${block('Palette — raw scales', 'Never read directly by a component. Present so the layer above can alias into it.', flatten(tokens.palette, ['palette']))}
${block('Semantic — what a colour means', 'Surfaces, text roles, and the six meanings with primary, secondary and tint.', flatten(tokens.color, ['color']))}
${block('Purpose — where a colour is used', 'The name of the one place a colour is used. Always an alias into semantic.', flatten(tokens.purpose, ['purpose']))}
${block('Space — one scale', 'The dash face’s spacing scale, in px, reused for the page’s own rhythm.', scale(tokens.space as Record<string, unknown>, 'space', 'px'))}
${block('Radius — hard edges', 'Rule 7. The site is as square as the dash; 2 exists for the wordmark mark and nothing else.', scale((tokens.radius as Record<string, unknown>) ?? {}, 'radius', 'px'))}}
`;
}

if (import.meta.main) {
  const tokens = JSON.parse(await Bun.file(tokensPath).text()) as Record<string, unknown>;
  mkdirSync(path.dirname(outPath), { recursive: true });
  writeFileSync(outPath, stylesheet(tokens));
  const count = [tokens.palette, tokens.color, tokens.purpose].reduce((n, group) => n + flatten(group).length, 0);
  console.log(`wrote ${path.relative(repoRoot, outPath)} (${count} colour tokens from tokens ${(tokens.$meta as Node)?.version})`);
}
