import type { Metadata } from 'next';
import Link from 'next/link';
import Image from 'next/image';
import { Reveal } from '../../components/Reveal';
import { SectionHead } from '../../components/SectionHead';
import styles from './page.module.css';

export const metadata: Metadata = {
  title: 'The flag box',
  description:
    'An 8x8 WS2812b matrix beside the screen showing the flag that is out, the gear, the pit state, a car alongside and the warnings you would otherwise miss. Sixty-nine pictures, one at a time, in priority order.',
};

/** The top of the priority table in docs/flag-box.md: everything above takes the panel from below. */
const PRIORITY = [
  { n: 1, what: 'Red — the whole box red', critical: true },
  { n: 2, what: 'Disqualified — a cross, blinking', critical: true },
  { n: 3, what: 'Black — an outline', critical: true },
  { n: 4, what: 'Black furled — a bar', critical: true },
  { n: 5, what: 'Meatball — an orange disc', critical: true },
  { n: 6, what: 'Chequered — a checkerboard', critical: false },
  { n: 7, what: 'Full-course caution — yellow in bands', critical: true },
  { n: 8, what: 'Waved yellow — yellow, blinking', critical: true },
  { n: 9, what: 'Yellow — solid, steady', critical: true },
  { n: 10, what: 'Debris — yellow with danger stripes', critical: true },
  { n: 11, what: 'Blue — an arrow that moves', critical: true },
  { n: 12, what: 'White — the last lap', critical: false },
];

export default function FlagBox() {
  return (
    <>
      <section className={`section ${styles.top}`}>
        <div className="page">
          <SectionHead level="h1" label="Lights" title={<>Sixty-four LEDs that tell you to lift.</>}>
            <p>
              An <strong>8×8 WS2812b matrix</strong> on an Arduino, beside your screen — the printed
              box a lot of people already have. It shows the flag that is out, the gear, the pit
              state, a car alongside, and the warnings you would otherwise miss.
            </p>
            <p>
              SimHub drives the hardware natively; OpenDash only supplies what it shows. The profile
              works without the plugin, because every setting it reads has a default built in.
            </p>
          </SectionHead>
        </div>
      </section>

      {/* ------------------------------------------------------------ the glyphs */}
      <section className={`section ruled ${styles.block}`}>
        <div className="page">
          <SectionHead label="The catalogue" title={<>Sixty-nine pictures, one at a time.</>}>
            <p>
              Every glyph the box can draw, at the size it is actually drawn: eight pixels by eight.
              That is the whole constraint — a flag has to be legible in sixty-four squares at the
              edge of your vision, which is why the blue flag is an arrow that moves rather than a
              blue square that could be anything.
            </p>
          </SectionHead>

          <Reveal>
            <figure className={styles.sheet}>
              <Image
                src="/flag-box.svg"
                alt="Every glyph the OpenDash flag box can draw, each on an 8 by 8 grid"
                width={616}
                height={810}
                className={styles.sheetImg}
                unoptimized
              />
              <figcaption className={styles.caption}>
                Generated by the same build that writes the LED profile, so it is what your box will
                actually draw.
              </figcaption>
            </figure>
          </Reveal>
        </div>
      </section>

      {/* ------------------------------------------------------------ priority */}
      <section className={`section ruled ${styles.block}`}>
        <div className="page">
          <SectionHead label="Priority" title={<>One picture at a time.</>}>
            <p>
              Everything higher in this list takes the panel from everything lower, so you can learn
              the box away from the car. <strong>Critical flags only</strong> is a switch that keeps
              everything meaning <em>slow down</em> or addressed to you, and drops the rest.
            </p>
          </SectionHead>

          <Reveal>
            <ol className={styles.priority}>
              {PRIORITY.map((p) => (
                <li key={p.n} className={styles.rank}>
                  <span className={`num ${styles.rankN}`}>{p.n}</span>
                  <span className={styles.rankWhat}>{p.what}</span>
                  {p.critical ? (
                    <span className={styles.critical} title="Kept by ‘critical flags only’">
                      Critical
                    </span>
                  ) : (
                    <span className={styles.quiet}>Dropped when quiet</span>
                  )}
                </li>
              ))}
            </ol>
            <p className={styles.after}>
              …and below them the pit states, the spotter, and the fuel, oil and water warnings.
            </p>
          </Reveal>
        </div>
      </section>

      {/* ------------------------------------------------------------ setting it up */}
      <section className={`section ruled ${styles.block}`}>
        <div className="page">
          <SectionHead label="Setting it up" title={<>Two settings on the device, first.</>}>
            <p>
              This is the step everybody gets wrong, and the symptom is that the profile looks
              broken. Both belong to SimHub’s device page rather than to OpenDash, because they are
              facts about <em>your</em> box — which corner the data cable enters — and two places to
              set them would be two places to disagree.
            </p>
          </SectionHead>

          <div className={styles.cards}>
            <Reveal className={styles.card}>
              <h3 className="h3">Rotation</h3>
              <p className="prose">
                Get it wrong and everything is sideways or upside down. The gear is the giveaway: a{' '}
                <span className="num">3</span> that reads as an <strong>E</strong> is a rotation, not
                a bug.
              </p>
            </Reveal>

            <Reveal delay={80} className={styles.card}>
              <h3 className="h3">Serpentine</h3>
              <p className="prose">
                Get it wrong and alternate rows run backwards: a chequered flag comes out as diagonal
                stripes, and the gear looks shredded.
              </p>
            </Reveal>

            <Reveal delay={160} className={styles.card}>
              <h3 className="h3">Mounted</h3>
              <p className="prose">
                Where the box physically is — not what you want it to show. A box on the left of your
                wheel that lights for a car on your <em>right</em> is worse than no box at all. With
                one box, leave it on <strong>Both</strong>.
              </p>
            </Reveal>

            <Reveal delay={240} className={styles.card}>
              <h3 className="h3">Never installed for you</h3>
              <p className="prose">
                OpenDash never installs the profile on its own. A profile paints hardware you own,
                and that is a thing to be asked about rather than assumed. Press{' '}
                <strong>Install into SimHub</strong> on the plugin’s Lights page.
              </p>
            </Reveal>
          </div>

          <Reveal delay={300}>
            <p className={styles.after}>
              SimHub composes up to four matrix contents, so you can run more than one box — one in
              each corner of the monitor stand, flags on the left and the spotter on the right, is
              the setup people build on day one. Everything on this page is in the plugin, on the{' '}
              <strong>Lights</strong> page, next to twenty wheel-LED profiles for the rim.{' '}
              <Link href="/download" className="link">
                Get the plugin
              </Link>
              .
            </p>
          </Reveal>
        </div>
      </section>
    </>
  );
}
