/**
 * The advance table against the fonts it says it came from.
 *
 * `design/advances.ts` is generated by `tools/measure-font` and then committed, so nothing has ever
 * compared the two: every fit test in this repository measures against the table, which means a
 * mistyped number is a number every test agrees with and WPF does not. A character budget makes that
 * worse rather than better — `charsThatFit` divides a box by one entry of the table — so the entries
 * are checked here against the files the package ships.
 */
import { describe, expect, test } from 'bun:test';
import { ELLIPSIS, FALLBACK_ADVANCE, charsThatFit, measureText, widestGlyph, widestOf, type MeasuredFace } from '../src/design/advances.ts';

/** Which bundled file each measured face is measured from. */
const FILES: Record<MeasuredFace, string> = {
  BarlowMedium: 'Barlow-Medium.ttf',
  BarlowBold: 'Barlow-Bold.ttf',
  BarlowCondensedSemiBold: 'BarlowCondensed-SemiBold.ttf',
  BarlowCondensedBold: 'BarlowCondensed-Bold.ttf',
  BarlowCondensedLight: 'BarlowCondensed-Light.ttf',
};

const FACES = Object.keys(FILES) as MeasuredFace[];

/** Every character any face's table carries, which is the same set for all five. */
const CHARACTERS = [...' !"#$%&\'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\\]^_`abcdefghijklmnopqrstuvwxyz{|}~', '°', '·', '−', '–', 'Δ', ELLIPSIS];

describe('the advance table is the fonts', () => {
  for (const face of FACES) {
    test(`${face} advances every character as its file does`, async () => {
      const { loadFont, measure } = await import('../../../tools/measure-font/measure.ts');
      const font = loadFont(`packages/dash/fonts/${FILES[face]}`);
      for (const ch of CHARACTERS) {
        const m = measure(font, ch);
        if (!m) throw new Error(`${FILES[face]} has no glyph for ${JSON.stringify(ch)}`);
        // Rounded to the three decimals the table carries. A one-thousandth disagreement is the table
        // being stale rather than the tool being imprecise.
        expect({ face, ch, table: Math.round(measureText(face, ch, 1000)) / 1000, font: Math.round(m.advance * 1000) / 1000 }).toMatchObject({
          table: Math.round(m.advance * 1000) / 1000,
        });
      }
    });
  }
});

describe('the widest glyph, which is what a character budget is measured by', () => {
  test('it is the widest entry the face carries, and the fallback is under it', () => {
    // The fallback covers a character the table does not carry, which in a driver name is an accented
    // letter. Every one of those is a narrower letter than W, so the budget holds them too — and if the
    // fallback ever rose above the widest measured glyph, `widestOf` would declare a `widest` narrower
    // than what the item could draw and the fit tests would stop being a promise.
    for (const face of FACES) {
      const { glyph, advance } = widestGlyph(face);
      const widest = Math.max(...CHARACTERS.map((ch) => measureText(face, ch, 1)));
      expect({ face, glyph, advance }).toMatchObject({ advance: widest });
      expect({ face, over: FALLBACK_ADVANCE <= advance }).toMatchObject({ over: true });
    }
    // In the name face it is the W, which is what makes a character budget a letter's width rather
    // than a per-cent sign's: `%` is the widest glyph of the three condensed faces and no part of a
    // name, but the name face is Barlow Medium and there the W is wider than it.
    expect(widestGlyph('BarlowMedium').glyph).toBe('W');
  });

  test('a budget is strictly inside its box, at every size and width', () => {
    // Strict, because WPF clips at the edge and the fit tests ask for `width < box`. The off-by-one
    // this guards is the exactly-divisible case: a 10 px box at an advance of exactly 10 holds nought
    // characters, not one.
    for (const face of FACES) {
      const advance = widestGlyph(face).advance;
      for (const fs of [12, 13, 15, 16, 24, 34]) {
        for (const width of [0, 1, 20, 57, 64, 82, 138, 190, 745, Math.ceil(8 * advance * fs), Math.floor(8 * advance * fs)]) {
          const chars = charsThatFit(face, fs, width);
          expect({ face, fs, width, chars, fits: chars === 0 || measureText(face, widestOf(face, chars), fs) < width }).toMatchObject({ fits: true });
          // And it is the largest such count: one more would not fit.
          expect({ face, fs, width, chars, tight: measureText(face, widestOf(face, chars + 1), fs) >= width }).toMatchObject({ tight: true });
        }
      }
    }
  });

  test('an ellipsis is narrower than the glyph the budget assumes, in every face', () => {
    // What lets a cut text of `chars` characters be measured as `chars` of the widest glyph: the last
    // of them is the ellipsis, and the ellipsis is the narrower of the two everywhere.
    for (const face of FACES) {
      expect({ face, narrower: measureText(face, ELLIPSIS, 1) < widestGlyph(face).advance }).toMatchObject({ narrower: true });
    }
  });
});
