/**
 * The advance table against the fonts it says it came from.
 *
 * `design/advances.ts` is generated by `tools/measure-font` and then committed, so nothing has ever
 * compared the two: every fit test in this repository measures against the table, which means a
 * mistyped number is a number every test agrees with and WPF does not. A character budget makes that
 * worse rather than better — `charsThatFit` divides a box by one entry of the table — so the entries
 * are checked here against the files the package ships.
 */
import { describe, expect, test } from 'bun:test';
import { ELLIPSIS, FALLBACK_ADVANCE, TITTLE_BREAK, charsThatFit, dottedLetterSize, measureText, widestGlyph, widestOf, type SegmentFace, type TextFace } from '../src/design/advances.ts';
import { UNTIMED_MARK } from '../src/second/values.ts';

/** Which bundled file each measured face is measured from. */
const FILES: Record<TextFace, string> = {
  BarlowMedium: 'Barlow-Medium.ttf',
  BarlowBold: 'Barlow-Bold.ttf',
  BarlowCondensedSemiBold: 'BarlowCondensed-SemiBold.ttf',
  BarlowCondensedBold: 'BarlowCondensed-Bold.ttf',
  BarlowCondensedLight: 'BarlowCondensed-Light.ttf',
};

const FACES = Object.keys(FILES) as TextFace[];

/**
 * The segment faces a theme ships (#204), which carry fewer characters than Barlow: no `#`, no `;`,
 * no brackets, and DSEG7 none of the punctuation a seven-segment cell cannot draw. Their tables hold
 * exactly the characters the file has, so a character outside them falls back as an accented letter
 * does in Barlow, and is measured at the fallback rather than at a width the face never drew.
 */
const SEGMENT_FILES: Record<SegmentFace, string> = {
  DSEG7Regular: 'DSEG7Classic-Regular.ttf',
  DSEG7Bold: 'DSEG7Classic-Bold.ttf',
  DSEG14Regular: 'DSEG14Classic-Regular.ttf',
};

/** Every character any face's table carries, which is the same set for all five. */
const CHARACTERS = [...' !"#$%&\'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\\]^_`abcdefghijklmnopqrstuvwxyz{|}~', '°', '·', '−', '–', 'Δ', ELLIPSIS, UNTIMED_MARK];

describe('the advance table is the fonts', () => {
  for (const face of FACES) {
    test(`${face} advances every character as its file does`, async () => {
      const { loadFont, measure } = await import('../../../tools/measure-font/measure.ts');
      const font = loadFont(`packages/dash/fonts/${FILES[face]}`);
      for (const ch of CHARACTERS) {
        const m = measure(font, ch);
        if (!m) throw new Error(`${FILES[face]} has no glyph for ${JSON.stringify(ch)}`);
        // Rounded to the three decimals the table carries. A one-thousandth disagreement is the table
        // being stale rather than the tool being imprecise.
        expect({ face, ch, table: Math.round(measureText(face, ch, 1000)) / 1000, font: Math.round(m.advance * 1000) / 1000 }).toMatchObject({
          table: Math.round(m.advance * 1000) / 1000,
        });
      }
    });
  }
});

describe('the segment faces are their fonts', () => {
  for (const face of Object.keys(SEGMENT_FILES) as SegmentFace[]) {
    test(`${face} advances every character it carries as its file does, and carries none the file has not`, async () => {
      const { loadFont, measure } = await import('../../../tools/measure-font/measure.ts');
      const font = loadFont(`packages/dash/fonts/${SEGMENT_FILES[face]}`);
      for (const ch of CHARACTERS) {
        const m = measure(font, ch);
        const table = Math.round(measureText(face, ch, 1000)) / 1000;
        expect({ face, ch, table }).toMatchObject({ table: m ? Math.round(m.advance * 1000) / 1000 : FALLBACK_ADVANCE });
      }
      // The fallback is under the cell, so a character a segment face does not carry is inside any
      // box measured from the face's own glyphs.
      expect({ face, under: FALLBACK_ADVANCE <= widestGlyph(face).advance }).toMatchObject({ under: true });
    });
  }
});

describe('the widest glyph, which is what a character budget is measured by', () => {
  test('it is the widest entry the face carries, and the fallback is under it', () => {
    // The fallback covers a character the table does not carry, which in a driver name is an accented
    // letter. Every one of those is a narrower letter than W, so the budget holds them too — and if the
    // fallback ever rose above the widest measured glyph, `widestOf` would declare a `widest` narrower
    // than what the item could draw and the fit tests would stop being a promise.
    for (const face of FACES) {
      const { glyph, advance } = widestGlyph(face);
      const widest = Math.max(...CHARACTERS.map((ch) => measureText(face, ch, 1)));
      expect({ face, glyph, advance }).toMatchObject({ advance: widest });
      expect({ face, over: FALLBACK_ADVANCE <= advance }).toMatchObject({ over: true });
    }
    // In the name face it is the W, which is what makes a character budget a letter's width rather
    // than a per-cent sign's: `%` is the widest glyph of the three condensed faces and no part of a
    // name, but the name face is Barlow Medium and there the W is wider than it.
    expect(widestGlyph('BarlowMedium').glyph).toBe('W');
  });

  test('a budget is strictly inside its box, at every size and width', () => {
    // Strict, because WPF clips at the edge and the fit tests ask for `width < box`. The off-by-one
    // this guards is the exactly-divisible case: a 10 px box at an advance of exactly 10 holds nought
    // characters, not one.
    for (const face of FACES) {
      const advance = widestGlyph(face).advance;
      for (const fs of [12, 13, 15, 16, 24, 34]) {
        for (const width of [0, 1, 20, 57, 64, 82, 138, 190, 745, Math.ceil(8 * advance * fs), Math.floor(8 * advance * fs)]) {
          const chars = charsThatFit(face, fs, width);
          expect({ face, fs, width, chars, fits: chars === 0 || measureText(face, widestOf(face, chars), fs) < width }).toMatchObject({ fits: true });
          // And it is the largest such count: one more would not fit.
          expect({ face, fs, width, chars, tight: measureText(face, widestOf(face, chars + 1), fs) >= width }).toMatchObject({ tight: true });
        }
      }
    }
  });

  test('an ellipsis is narrower than the glyph the budget assumes, in every face', () => {
    // What lets a cut text of `chars` characters be measured as `chars` of the widest glyph: the last
    // of them is the ellipsis, and the ellipsis is the narrower of the two everywhere.
    for (const face of FACES) {
      expect({ face, narrower: measureText(face, ELLIPSIS, 1) < widestGlyph(face).advance }).toMatchObject({ narrower: true });
    }
  });
});

/**
 * And the other half of a glyph a fit test cannot see: where its ink breaks.
 *
 * An advance says how much room a letter takes and says nothing about whether the letter survives
 * being drawn at that size. Barlow's `i` is a stem with a dot floating 0.080 em above it, and at 13 px
 * the VM's relative drew four of nine names with the dot welded to the stem: `Llam B…`, `NIna H…`,
 * `Sofla …`, `Henrlk…`. The break is what decides that, so it is read off the outlines here and the
 * name column's case rule is built on it rather than on the screenshot.
 */
describe('the break inside a glyph, which is what the name column is cased by', () => {
  for (const face of FACES) {
    test(`${face} breaks its i at the number the table quotes, and no letter but the j at all`, async () => {
      const { inkBreak, loadFont } = await import('../../../tools/measure-font/measure.ts');
      const font = loadFont(`packages/dash/fonts/${FILES[face]}`);
      // Nothing here may answer `undefined`, which is an outline the tool declined to read: a `?? 0`
      // over one of those would turn "not measured" into "not broken" and pass.
      const measured = CHARACTERS.map((ch) => [ch, inkBreak(font, ch)] as const);
      expect({ face, unread: measured.filter(([, gap]) => gap === undefined).map(([ch]) => ch) }).toMatchObject({ unread: [] });
      // Letters only: `!`, `?`, `;` and the ellipsis break too and are not letters.
      expect({ face, letters: measured.filter(([ch, gap]) => (gap ?? 0) > 0 && /[A-Za-z]/.test(ch)).map(([ch]) => ch) }).toMatchObject({ letters: ['i', 'j'] });
      // The one number `dottedLetterSize` divides two device pixels by, against the file it is quoted
      // from, rounded to the three decimals the table carries. The *table* is what is asserted and the
      // measurement is what it is asserted against, not the other way about: an entry compared with
      // itself would be a tautology, and this number is quoted in three documents as well as in code.
      const tittle = Math.round((inkBreak(font, 'i') ?? 0) * 1000) / 1000;
      expect({ face, table: TITTLE_BREAK[face], font: tittle }).toMatchObject({ table: tittle });
      // The `j` is held *against* the entry rather than to it, one number per face not being able to be
      // both: Barlow Bold breaks its `j` at 0.058 em where its `i` breaks at 0.057. The `i` is the
      // tighter of the two in all five faces, which is what makes the entry the bound for the pair.
      const hook = Math.round((inkBreak(font, 'j') ?? 0) * 1000) / 1000;
      expect({ face, table: TITTLE_BREAK[face], j: hook, holds: hook >= TITTLE_BREAK[face] }).toMatchObject({ holds: true });
    });
  }

  test('no unaccented upper-case letter and no digit is drawn in two pieces, which is what upper case removes', async () => {
    // The argument for shouting a name at a small size. Shouting is not more legible in general; it is
    // that the failure needs a glyph with a gap in it, and the unaccented upper-case alphabet has none,
    // so `LIAM BYRNE` cannot be read as another name the way `Liam Byrne` was. A counter does not
    // count: the spans are merged before the gaps are measured, so the hole in an `O` is inside the
    // letter and not a break.
    const { inkBreak, loadFont } = await import('../../../tools/measure-font/measure.ts');
    for (const face of FACES) {
      const font = loadFont(`packages/dash/fonts/${FILES[face]}`);
      // `undefined` rather than 0 would be an outline the tool declined, and would make the assertion
      // vacuous — so the answer is compared as it comes back.
      for (const ch of 'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789 -') {
        expect({ face, ch, break: inkBreak(font, ch) }).toMatchObject({ break: 0 });
      }
    }
  });

  test('an accented capital keeps its floating mark, so the case rule removes a substitution and not a class', async () => {
    // The limit of the row above, in numbers rather than left to an absolute that is not one. An
    // accented capital is a letter with a mark placed over it, so it has the same construction the
    // lowercase `i` failed at — and four of these seven break *tighter* in the name face than the
    // 0.080 em the `i` does, every one of them under the two device pixels 13 and 15 px can promise.
    // RÄIKKÖNEN may therefore still come back with a mark welded to its letter.
    //
    // What upper case removes is the *substitution*. A welded tittle makes `Liam` a legal `Llam`, a
    // different name that reads as itself; a welded acute makes `É` a misdrawn `É`, which is still the
    // letter and still the name. There is no tighter bound to reach for: these are the marks the five
    // bundled faces draw, and the alternative to drawing them is not drawing the name.
    const { inkBreak, loadFont } = await import('../../../tools/measure-font/measure.ts');
    const font = loadFont('packages/dash/fonts/Barlow-Medium.ttf');
    // `-1` rather than 0 for an outline the tool declined, so a composite it stopped resolving fails
    // here instead of reading as a letter drawn in one piece.
    const breaks = Object.fromEntries([...'ÉÅÍÖÄÜÑ'].map((ch) => [ch, Math.round((inkBreak(font, ch) ?? -1) * 1000) / 1000]));
    expect(breaks).toEqual({ É: 0.064, Å: 0.064, Í: 0.064, Ö: 0.076, Ä: 0.084, Ü: 0.084, Ñ: 0.084 });
    expect({ tighterThanTheI: Object.entries(breaks).filter(([, gap]) => gap < TITTLE_BREAK.BarlowMedium).map(([ch]) => ch) }).toMatchObject({
      tighterThanTheI: ['É', 'Å', 'Í', 'Ö'],
    });
  });

  test('a heavier weight closes the gap rather than opening it', () => {
    // The candidate remedy that reads as obvious and is measurably backwards. A fatter stem and a
    // fatter dot are drawn into the same vertical, so the room between them is what gives way: in the
    // condensed family the break falls from 0.101 em at Light to 0.070 at SemiBold to 0.058 at Bold.
    expect(TITTLE_BREAK.BarlowCondensedLight).toBeGreaterThan(TITTLE_BREAK.BarlowCondensedSemiBold);
    expect(TITTLE_BREAK.BarlowCondensedSemiBold).toBeGreaterThan(TITTLE_BREAK.BarlowCondensedBold);
    expect(TITTLE_BREAK.BarlowMedium).toBeGreaterThan(TITTLE_BREAK.BarlowBold);
  });

  test('two device pixels of break is 25 px in the name face, above every size a list draws a name at', () => {
    // Which is what makes the case rule cover every table rather than the one row the VM photographed:
    // 15 px from the 34 px row up, 13 in the narrow zone's, 12 on a companion, and a board's 15.
    expect(dottedLetterSize('BarlowMedium')).toBe(25);
    for (const fs of [12, 13, 15]) expect({ fs, safe: fs >= dottedLetterSize('BarlowMedium') }).toMatchObject({ safe: false });
    // And it is a bound that a big enough size really does clear, rather than one nothing can reach.
    expect({ safe: 34 >= dottedLetterSize('BarlowMedium') }).toMatchObject({ safe: true });
  });
});
