import type { Metadata } from 'next';
import Image from 'next/image';
import Link from 'next/link';
import { Attribution } from '../../components/Attribution';
import { Capture } from '../../components/Capture';
import { Priority } from '../../components/Priority';
import { Section } from '../../components/Section';
import { StripGrid } from '../../components/StripGrid';
import { CAPTURES, panelFile } from '../../lib/captures';
import { STRIP_SHAPES } from '../../lib/content.generated';
import styles from './page.module.css';

export const metadata: Metadata = {
  title: 'Lights: the car’s own shift lights',
  description: '62 strip shapes and an 8 × 8 flag box. Shift lights in your car’s own colours and order, from open data.',
};

export default function Lights() {
  const panel = CAPTURES.files[panelFile('lights')];

  return (
    <>
      <Section
        level={1}
        ruled={false}
        id="car"
        label="Lights"
        title="Your car’s own shift lights, on any strip."
        lede={`OpenDash lights an LED strip in the colours, order and per-gear thresholds of the car you drive. ${STRIP_SHAPES.length} strip shapes and an 8 × 8 flag box, all generated by the same build as the dashboards.`}
        wide
      >
        <div className={styles.columns}>
          <div className={styles.column}>
            <h2 className="h3">Where the lights come from</h2>
            <p className="prose">
              The plugin fetches 1 table of every car from Lovely Car Data when you press Download on the Lights tab. About 400 KB, once. Nothing about the car you
              drive leaves your machine. OpenDash does not bundle the data.
            </p>
            <Attribution className={`prose ${styles.credit}`} />
          </div>
          <div className={styles.column}>
            <h2 className="h3">Without a table</h2>
            <p className="prose">
              A car without a table gets the 4 shift RPMs iRacing publishes for it. A car that publishes none gets SimHub’s bands. Without the plugin, the
              profile still lights, using the same fallback.
            </p>
          </div>
        </div>
      </Section>

      <Section
        id="strips"
        label="Strip shapes"
        title={`${STRIP_SHAPES.length} strip shapes.`}
        lede="A strip is sides and a centre: 0 to 4 LEDs each side, 4 to 12 in the middle. Bare runs of 13 to 25 for brows. 5 legacy shapes for wheels people already own. Pick your shape by counting, not by brand."
        wide
      >
        <StripGrid />
      </Section>

      <Section
        id="strip-shows"
        label="Beyond the revs"
        title="What else the strip shows."
        lede="The sides are lamps. Flags, a car alongside, pit states and warnings, ranked the way the face ranks them."
        wide
      >
        <Priority />
      </Section>

      <Section
        id="flag-box"
        label="Flag box"
        title="The flag box."
        lede="An 8 × 8 WS2812b matrix on an Arduino, beside the screen. 69 glyphs, 1 at a time, in priority order: the flag that is out, the pit state, warnings, then the gear."
        wide
      >
        <div className={styles.box}>
          <figure className={styles.sheet}>
            <Image src="/flag-box.svg" alt="Every glyph the flag box can draw, each on an 8 by 8 grid" width={616} height={810} unoptimized className={styles.sheetImg} />
            <figcaption className={styles.caption}>Generated by the build that writes the profile.</figcaption>
          </figure>
          <div className={styles.boxText}>
            <div className={styles.point}>
              <h3 className="h3">Set the device up first</h3>
              <p className="prose">Set rotation and serpentine on the device in SimHub before anything else. Wrong values make the picture sideways or shredded.</p>
            </div>
            <div className={styles.point}>
              <h3 className="h3">Mounting side is where the box is</h3>
              <p className="prose">Not what it shows. A box on the left that lights for a car on the right is worse than no box.</p>
            </div>
            <div className={styles.point}>
              <h3 className="h3">Never installed for you</h3>
              <p className="prose">OpenDash never installs a profile by itself. Press Install on the Lights tab.</p>
            </div>
            <div className={styles.point}>
              <h3 className="h3">Checked, not yet driven</h3>
              <p className="prose">No matrix is plugged into the test machine. The glyphs are checked in tests and in SimHub’s preview, not yet on a real panel.</p>
            </div>
          </div>
        </div>
      </Section>

      <Section
        id="tab"
        label="The Lights tab"
        title="Everything above, on 1 tab."
        lede="The flag box and up to 4 matrix panels, a low fuel warning in laps, a strip per device with its centre display and rev light style, the car light tables with their update button, and brightness, night brightness and night mode for every light."
        wide
      >
        <Capture file={panelFile('lights')} alt="The plugin’s Lights tab in SimHub" width={panel?.width ?? 1200} height={panel?.height ?? 1300} caption="The Lights tab" scale={1} />
        <p className={`prose ${styles.more}`}>
          <Link href="/install" className="link">
            How to install the plugin
          </Link>
        </p>
      </Section>
    </>
  );
}
