import type { Metadata } from 'next';
import Image from 'next/image';
import Link from 'next/link';
import { Attribution } from '../../components/Attribution';
import { LedStrip } from '../../components/LedStrip';
import { FRAMES } from '../../lib/stripFrames';
import { Priority } from '../../components/Priority';
import { Section } from '../../components/Section';
import { StripGrid } from '../../components/StripGrid';
import { STRIP_SHAPES } from '../../lib/content.generated';
import { COUNTS } from '../../lib/liveCounts';
import { INSTALL } from '../../lib/site';
import styles from './page.module.css';

export const metadata: Metadata = {
  title: 'Lights: the car’s own shift lights',
  description: `${COUNTS.stripShapes} strip shapes and an 8 × 8 flag box. Shift lights in your car’s own colours and order, and the sides for flags, the spotter and warnings.`,
};

/** The states the examples show, drawn by the site. */
const EXAMPLES = [FRAMES.shift!, FRAMES.blue!, FRAMES.yellow!, FRAMES.spotter!, FRAMES.fuel!, FRAMES.abs!, FRAMES.limiter!];

export default function Lights() {
  return (
    <>
      <Section
        level={1}
        ruled={false}
        id="car"
        title="Your car’s own shift lights, on any strip"
        lede="Every car has its own shift lights: the colours, the order, the revs each one comes on at. OpenDash lights your strip the way the real car does, and uses the sides for what matters."
      >
        <div className={styles.demo}>
          <LedStrip left={3} centre={9} right={3} live led={22} gap={8} />
          <p className={`prose ${styles.aside}`}>A 3/9/3 strip, drawn by the site. Each side is three single lamps, counted from the outside in: a car alongside, then flags, then your car and the aids. ABS lights the left end and traction control the right. The pit limiter takes the whole strip.</p>
        </div>
        <div className={styles.columns}>
          <div className={styles.column}>
            <h2 className="h3">Lit like the real car</h2>
            <p className="prose">
              A Porsche lights like a Porsche and a Ferrari like a Ferrari. The shift points come from Lovely Car Data, an open table of measured cars. One
              click on the LEDs page fetches it, and nothing about you or your car leaves your machine.
            </p>
            <Attribution className={`prose ${styles.credit}`} />
          </div>
          <div className={styles.column}>
            <h2 className="h3">Every strip, every wheel</h2>
            <p className="prose">
              Pick your strip by counting its LEDs: sides and centre. {STRIP_SHAPES.length} shapes are included, from a 3/9/3 rim to a 25-LED brow, and any
              device SimHub drives can have one. Every shape on the grid can be wired from either end. A car without a table still gets the shift points iRacing publishes for it.
            </p>
          </div>
        </div>
      </Section>

      <Section
        id="strips"
        title={`${STRIP_SHAPES.length} strip shapes`}
        lede="A strip is sides and a centre: 0 to 4 LEDs each side, 4 to 12 in the middle, and bare runs up to 25 for a brow. Pick yours by counting, not by brand."
      >
        <StripGrid />
      </Section>

      <Section id="strip-shows" title="LEDs, for more than revs" lede="The sides light for what matters in the moment: a flag, a car alongside, the limiter, a warning. The first thing on the list that is true takes the lamp.">
        <ul className={styles.examples}>
          {EXAMPLES.map((f) => (
            <li key={f.label} className={styles.example}>
              <LedStrip left={3} centre={9} right={3} frame={f} led={14} gap={5} />
            </li>
          ))}
        </ul>
        <p className={`prose ${styles.aside}`}>In order of what takes the flag lamp:</p>
        <div className={styles.priority}>
          <Priority />
        </div>
      </Section>

      <Section
        id="flag-box"
        title="The flag box"
        lede={`An 8 × 8 WS2812b matrix on an Arduino, beside the screen. ${COUNTS.glyphs} glyphs, one at a time, in priority order: the flag that is out, the pit state, the warnings, then the gear.`}
      >
        <div className={styles.box}>
          <figure className={styles.sheet}>
            <Image src="/flag-box.svg" alt="Every glyph the flag box can draw, each on an 8 by 8 grid" width={616} height={810} unoptimized className={styles.sheetImg} />
            <figcaption className={styles.caption}>Generated by the build that writes the profile.</figcaption>
          </figure>
          <div className={styles.boxText}>
            <div className={styles.point}>
              <h3 className="h3">Set the device up first</h3>
              <p className="prose">Set rotation and serpentine on the device in SimHub before anything else. Wrong values make the picture sideways or shredded.</p>
            </div>
            <div className={styles.point}>
              <h3 className="h3">Mounting side is where the box is</h3>
              <p className="prose">Not what it shows. A box on the left that lights for a car on the right is worse than no box.</p>
            </div>
            <div className={styles.point}>
              <h3 className="h3">Never installed for you</h3>
              <p className="prose">OpenDash never installs a profile by itself. Press Install at the top of the Matrix page.</p>
            </div>
            <div className={styles.point}>
              <h3 className="h3">Checked, not yet driven</h3>
              <p className="prose">No matrix is plugged into the test machine. The glyphs are checked in tests and in SimHub’s preview, not yet on a real panel.</p>
            </div>
          </div>
        </div>
      </Section>

      <Section
        id="plugin"
        title="In the plugin"
        lede="The LEDs page holds your strips, each with its rev lights, the car’s own rev lights and its centre display, and Lovely Car Data under Every strip. The Matrix page installs the flag box profile and holds its priority and up to four matrices. The Settings page holds the low fuel warning in laps, and brightness and night mode for every light."
      >
        <p className={`prose ${styles.more}`}>
          <Link href={INSTALL.href} className="link">
            How to install the plugin
          </Link>
        </p>
      </Section>
    </>
  );
}
